version: '3.8'

services:
  db:
    build: .
    container_name: postgres_db
    environment:
      POSTGRES_USER: fsantoliquido
      POSTGRES_PASSWORD: itba1234
      POSTGRES_DB: airlines
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/scripts/create_tables.sql
volumes:
  postgres_data:
  