FROM python:3.8-slim

# Instalar psycopg2
RUN pip install psycopg2-binary

# Crear directorio de trabajo
WORKDIR /scripts

# Copiar el script de Python y el archivo SQL al conteiner
COPY populate_db.py /scripts/
COPY transformed_inserts.sql /scripts/

# Aca ejecutamos el script
CMD ["python", "/scripts/populate_db.py"]